tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "caskformula/caskformula"
# Brew Apps
  brew "aspell"
  brew "awscli"
  brew "bash-completion"
  brew "bash"
  brew "git-extras"
  brew "git"
  brew "htop"
  brew "httpie"
  brew "Imagemagic"
  brew "jq"
  brew "mas"
  brew "pandoc"
  brew "pick"
  brew "shellcheck"
  brew "terraform"
  brew "tmux"
  brew "trash"
  brew "tree"
  brew "unrar"
  brew "vim"
  brew "wget"
  brew "youtube-dl"
  brew "htop"
  brew "imagemagick"
  brew "lua"
  brew "nmap"
  brew "inkscape"

# Casks
cask_args appdir: "/Applications"
  cask "atom"
  cask "cakebrew"
  cask "dropbox"
  cask "evernote"
  cask "flux"
  cask "google-chrome"
  cask "gpg-suite"
  cask "iterm2"
  cask "keepassxc"
  cask "slack"
  cask "steam"
  cask "transmission"
  cask "tunnelblick"
  cask "vlc"


# Mac App store (https://github.com/mas-cli/mas)
  mas "Magnet", id: 441258766
  mas "SomaFM", id: 449155338
  mas "Textual", id: 896450579
